export const playerExperienceCopy = {
  navigation: {
    label: "Primary navigation",
    today: "Today",
    team: "Team",
    me: "Me",
  },
  momentum: {
    eyebrow: "Your momentum",
    states: {
      ready: {
        label: "Ready",
        detail: "A fresh week starts with one good choice.",
      },
      started: {
        label: "Started",
        detail: "Your first plan day has the week moving.",
      },
      building: {
        label: "Building",
        detail: "Your steady choices are adding up.",
      },
      "on-a-roll": {
        label: "On a roll",
        detail: "You reached the team’s weekly plan goal.",
      },
    },
    thisWeek: "this week",
    preview: "Preview state",
    streak: (days: number) =>
      `${days.toLocaleString("en-US")}-day activity streak`,
    accessibleGauge: (sessions: number, goal: number) =>
      `Weekly Momentum: ${sessions} of ${goal} plan days`,
    guidanceLabel: "How to fill it",
    guidance: {
      goalComplete:
        "Weekly goal complete. Recovery is a good next move; there’s no need to add more.",
      remaining: (count: number) =>
        `${count.toLocaleString("en-US")} more ${count === 1 ? "plan day completes" : "plan days complete"} this week’s goal.`,
      recommendedPlan: "Today’s recommended plan is the clearest next step.",
      planComplete: "No need to add more today.",
      plannedRest: "Today, stick with planned recovery.",
    },
  },
  today: {
    eyebrow: "Today",
    log: "Log today’s plan",
    logPreview: "Goal or Reach · Effort · Tiredness",
    completionTitle: "Today is in the books",
    completionBody: "Your participation star is ready in Team.",
    joinTeam: "Join Team lounge",
    lockedTeamTitle: "Team lounge",
    lockedTeamBody: "Complete today’s plan to join your team.",
    unlockedTeamBody:
      "Your team is ready. Add your star and make the canvas move.",
    why: "Why this plan?",
  },
  whatsNext: {
    eyebrow: "What’s next",
    logPlan: "Log today’s plan",
    planFollowed: "Plan followed",
    completeTitle: "What’s next?",
    workoutLogged: "Today’s workout is in the books.",
    restLogged: "Planned rest logged",
    restTitle: "Planned recovery",
    restDetail:
      "Recovery is today’s plan. Check in to count it—no workout needed.",
    recordRest: "Record planned rest",
    previewOnly: "Preview only",
    saving: "Saving…",
    notYet: "Not yet",
    recommended: "Recommended next",
    lounge: "Relax in Team lounge",
    loungeDetail: "Cheer the team or add your stamp.",
    teamLocked: "Team lounge locked",
    teamLockedDetail: "Live access still follows the server gate.",
    cooldownLogged: "Cooldown logged",
    cooldownDetail: "Nice work bringing the effort back down.",
    logIfDone: "Already did it? Log",
    keepRecoveryEasy: "Keep recovery easy",
    keepRecoveryDetail: "Rest is the plan. No extra activity needed.",
    callItADay: "Or call it a day",
    callItADayDetail: "You have done enough for today.",
    saveError: "That workout could not be saved. Please try again.",
    actionError: "That could not be saved. Please try again.",
  },
  rewards: {
    eyebrow: "Team rewards coming soon",
    todayBody: "Show up together. Unlock something real.",
    teamBody: "Participation moves the whole team.",
    previewLabel: "Preview goal—not active yet",
    progress: "9 of 12 plan days",
  },
  teamPulse: {
    eyebrow: "Team pulse",
    title: "Latest from your team",
    activeThisWeek: (count: number) =>
      `${count.toLocaleString("en-US")} ${count === 1 ? "teammate has" : "teammates have"} shown up this week`,
    locked: "Team pulse unlocks after today’s check-in.",
    lockedDetail: "Finish the plan or submit prescribed rest to see it.",
    empty: "Your team’s next check-in will show here.",
    listLabel: "Recent team activity",
    cheer: "Cheer",
    cheering: "Sending…",
    cheered: "Cheered",
    privateDetail: "Cheers arrive privately.",
    failed: "That cheer could not be sent. Try again.",
  },
  previousViews: {
    eyebrow: "For comparison and review",
    title: "Previous views",
    body: "Open any earlier experience without changing the default view.",
  },
  devConsole: {
    title: "Experience dev console",
    summary: "Preview flags, visibility, and locked states",
    body: "These device-only presentation overrides never bypass server access or change saved training data.",
    momentumPreview: "Momentum preview",
    todayPreview: "Today preview",
    teamAccess: "Team access preview",
    showMomentum: "Show Momentum card",
    showRewards: "Show rewards preview",
    reset: "Reset dev controls",
    forcedLock: "Dev preview · locked presentation",
  },
} as const;
