export const playerExperienceCopy = {
  navigation: {
    label: "Primary navigation",
    today: "Today",
    team: "Team",
    me: "Me",
  },
  momentum: {
    eyebrow: "Your momentum",
    states: {
      ready: {
        label: "Ready",
      },
      started: {
        label: "Started",
      },
      building: {
        label: "Building",
      },
      "on-a-roll": {
        label: "On a roll",
      },
    },
    gaugeLabel: "Momentum",
    preview: "Preview state",
    streak: (days: number) =>
      `${days.toLocaleString("en-US")}-day check-in streak`,
    accessibleGauge: (score: number) =>
      `Momentum: ${score.toLocaleString("en-US")} out of 100`,
    guidanceLabel: "This week",
    firstCheckIn:
      "Your first check-in starts this week’s team target. Planned rest counts too.",
    weeklyProgress: (checkIns: number, remaining: number) =>
      `${checkIns.toLocaleString("en-US")} ${checkIns === 1 ? "check-in" : "check-ins"} this week. ${remaining.toLocaleString("en-US")} more ${remaining === 1 ? "reaches" : "reach"} your team’s target.`,
    weeklyComplete: (goal: number) =>
      `You reached your team’s ${goal.toLocaleString("en-US")}-check-in target this week. Nice consistency.`,
    improvementTip:
      "Show up on different days for the biggest lift. A second and third activity add smaller boosts; planned rest counts too.",
  },
  focusedToday: {
    today: "Today",
    details: "Details",
    hideDetails: "Hide details",
    startWorkout: "Start workout",
    startRecovery: "Start recovery day",
    confirmRecovery: "Complete recovery check-in",
    todayComplete: "Today complete",
    workoutCompleteBody: "Your workout check-in is saved.",
    recoveryCompleteBody: "Planned recovery logged. Today’s plan is complete.",
    recommended: "Recommended workout",
    recommendationFallback:
      "Nothing is scheduled today, so here’s a useful option.",
    coachPlan: "Coach plan",
    teamDefault: "Team default",
    restPurpose: "Rest supports consistency",
    restGoal: "Goal: Return refreshed and ready.",
    restInstruction:
      "Follow the plan and give your body the reset it needs. Hydrate, sleep well, and keep movement light.",
    weekTitle: "Your 7-day plan",
    fullPlan: "View full 7-day plan",
    fullPlanTitle: "Your plan",
    planDay: (current: number, total: number) => `Day ${current} of ${total}`,
    completed: "Completed",
    missed: "Missed",
    todayStatus: "Today",
    upcoming: "Upcoming",
    plannedRest: "Recovery",
    locked: "Locked",
    comeBack: (day: string) => `Come back ${day}`,
    planUnavailable: "No coach plan is available right now.",
    planLoadFailed: "Today’s plan could not be loaded",
    planLoadFailedBody:
      "Check your connection, then try again. No sample workout will be shown in its place.",
    activityUnavailable:
      "This planned activity needs an update from your coach before it can be recorded.",
    retry: "Try again",
    retrying: "Trying again…",
    saveError: "That workout could not be saved. Please try again.",
    actionError: "That could not be saved. Please try again.",
    finishPrompt: "Did you finish?",
    completedAsListed: "Did it!",
    finishedPart: "Almost…",
    addedExtra: "Extra!",
    backToToday: "Back to Today",
    overview: "Overview",
    coachNote: "Guidance",
    instructions: "What to do",
    futureNote:
      "You can see where this fits in the week. Instructions unlock that day.",
    otherTitle: "Other things you can do",
    teamLounge: "Team lounge",
    teamLoungeDetail: "Cheer the team or use your stamps.",
    teamLoungeLocked: "Complete today’s plan to enter.",
    logAnother: "Log another activity",
    logAnotherDetail: "Record something outside the planned workout.",
    prizeBoxes: "View prize boxes",
    prizeBoxesDetail: "See available, earned, or unopened rewards.",
    prizeBoxesUnopened: (count: number) =>
      `${count.toLocaleString("en-US")} unopened`,
    prizeBoxEarned: "Prize box earned! Saved to Prize boxes.",
    yourMomentum: "Your momentum",
    yourMomentumDetail: "View your check-in streak and progress.",
    momentumSummary: (score: number, streak: number) =>
      `Momentum ${score.toLocaleString("en-US")}, ${streak.toLocaleString("en-US")}-day check-in streak`,
    momentumGauge: (score: number) =>
      `Momentum ${score.toLocaleString("en-US")} out of 100`,
    momentumInfo:
      "Momentum rewards showing up. Planned workouts, recovery, rest check-ins, and bonus activities all help.",
  },
  today: {
    eyebrow: "Today",
    log: "Log today’s plan",
    logPreview: "Goal or Reach · Effort · Tiredness",
    completionTitle: "Today is in the books",
    completionBody: "Your participation star is ready in Team.",
    joinTeam: "Join Team lounge",
    lockedTeamTitle: "Team lounge",
    lockedTeamBody: "Complete today’s plan to join your team.",
    unlockedTeamBody:
      "Your team is ready. Add your star and make the canvas move.",
    why: "Why this plan?",
  },
  planTimeline: {
    regionLabel: "This week’s coach plan",
    coachPlan: "Coach plan",
    daysLabel: "Plan days",
    today: "Today",
    whatsNext: "What’s next",
    recoveryDay: "Recovery day",
    plannedRest: "Planned rest",
    restCheckedIn: "Rest checked in",
    completed: "Completed",
    missed: "Missed",
    missedDetail: "Missed—no catch-up needed",
    locked: "Locked",
    currentWorkout: "Current workout",
    swipeHint: "Swipe to explore plan days",
    jumpToday: "Jump back to today",
    policy:
      "Missed days stay missed. Your plan keeps moving—no catch-up workout.",
    comeBack: (day: string) => `Come back ${day}`,
  },
  rewards: {
    eyebrow: "Team rewards coming soon",
    todayBody: "Show up together. Unlock something real.",
    teamBody: "Participation moves the whole team.",
    previewLabel: "Preview goal—not active yet",
    progress: "9 of 12 plan days",
  },
  dailyDrop: {
    eyebrow: "Prize boxes",
    title: "A little something for showing up",
    body: "Open an available prize box. Opening one does not change Momentum.",
    earnedThreeDays: "Earned for completing 3 days in your coach plan.",
    earnedSevenDays: "Earned for completing all 7 days in your coach plan.",
    availableCount: (count: number) =>
      `${count.toLocaleString("en-US")} ${count === 1 ? "box" : "boxes"} ready to open`,
    loading: "Checking your prize boxes…",
    open: "Open prize box",
    openAnother: "Open another prize box",
    opening: "Opening…",
    tryOpeningAgain: "Try opening again",
    claimFailed: "Your drop is still sealed. Try again when you’re ready.",
    collected: "Collected today",
    unlocked: (label: string) => `Unlocked: ${label}`,
    avatarDestination: "Saved for Avatar Studio",
    canvasDestination: "Saved for Team lounge",
    collectionComplete: "Collection complete",
    collectionCompleteBody:
      "You found every item in this collection. Nice collecting.",
    loadFailed: "Today’s drop could not be loaded",
    tryAgain: "Try again",
  },
  teamPulse: {
    eyebrow: "Team pulse",
    title: "Latest from your team",
    activeThisWeek: (count: number) =>
      `${count.toLocaleString("en-US")} ${count === 1 ? "teammate has" : "teammates have"} shown up this week`,
    locked: "Team pulse unlocks after today’s check-in.",
    lockedDetail: "Finish the plan or submit prescribed rest to see it.",
    empty: "Your team’s next check-in will show here.",
    listLabel: "Recent team activity",
    cheer: "Cheer",
    cheering: "Sending…",
    cheered: "Cheered",
    showMore: "Show more",
    showLess: "Show less",
    showMoreLabel: "Show more team activity",
    showLessLabel: "Show less team activity",
    privateDetail: "Cheers arrive privately.",
    failed: "That cheer could not be sent. Try again.",
  },
  previousViews: {
    eyebrow: "For comparison and review",
    title: "Previous views",
    body: "Open any earlier experience without changing the default view.",
  },
  devConsole: {
    title: "Experience dev console",
    summary: "Preview flags, visibility, and locked states",
    body: "These device-only presentation overrides never bypass server access or change saved training data.",
    momentumPreview: "Momentum preview",
    todayPreview: "Today preview",
    teamAccess: "Team access preview",
    teamLoungeVersion: "Team Lounge version",
    showMomentum: "Show Momentum status",
    showRewards: "Show rewards preview",
    reset: "Reset dev controls",
    forcedLock: "Dev preview · locked presentation",
  },
} as const;
