export const worldCopy = {
  diagnostics: {
    title: "Dev controls",
    reference: "Independent motion reference",
    captureHelp:
      "After a stutter, save a capture immediately: it includes the last 10 seconds of movement, camera and frame timing. The moving reference uses a separate browser animation clock. Compare its smoothness with the avatar. Captures stay local until you share them.",
    download: "Save motion capture",
    help: "Render switches apply only to this browser and persist here. Try one switch at a time, then copy a report when ghosting appears. Normal rendering resets every switch. Plain materials bypass textures and custom shaders; there is no motion-blur pass.",
    ballTitle: "Pitch ball physics",
    ball: {
      gravity: "Gravity",
      speed: "Ball travel speed",
      friction: "Rolling friction",
    },
    ballReset: "Reset pitch balls",
    ballHost:
      "You host this room. Ball changes affect everyone here until you leave or hosting changes.",
    ballPeer:
      "The current room host controls shared ball physics. Sliders unlock when this browser hosts the room.",
    normal: "Normal rendering",
    minimal: "Minimal rendering",
    avatar: "Avatar rendering",
    model: "Avatar Studio model",
    capsule: "Simple capsule",
    material: "Scene materials",
    original: "Original materials",
    plain: "Plain normal colors",
    wireframe: "Wireframe",
    resolution: "Render resolution",
    silhouette: "Occlusion silhouette",
    comic: "Comic avatar shading",
    outlines: "Avatar ink outlines",
    animation: "Avatar animation",
    campus: "Campus art",
    freezeCamera: "Freeze camera",
    stats: (ms: number | undefined, calls: number | undefined) =>
      `Frame p95: ${ms?.toFixed(1) ?? "—"} ms · Draw calls: ${calls ?? "—"}`,
    copy: "Copy diagnostic report",
    copied: "Copied. Paste this report with what you saw.",
    selectReport: "Select and copy the report below.",
    report: "Diagnostic report",
  },
  navigation: {
    path: "Tap to travel · hold and steer · farther means faster",
    joystick: "Drag any open spot to walk · past the ring to sprint",
    landing: "Landing first · your next destination is queued",
    complex: "That route is too complex. Try a nearer spot.",
    unreachable: "No walking route to that spot",
    moving: "On the way · hold to steer or tap to redirect",
    arriving: "Arriving…",
    arrived: "You’re here · choose your next move",
    sprint: "Pace · automatic",
    sprintOn: "Pace · walk only",
  },
  lamp: {
    name: "Courtyard lamp",
    on: "Turn courtyard lamp on",
    off: "Turn courtyard lamp off",
  },
  soccer: {
    scoreboard: "Pitch score",
    main: "Main pitch",
    garden: "Garden pitch",
    burgundy: "Burgundy",
    gold: "Gold",
  },
  title: "Team World",
  fullscreen: "Full screen",
  exitFullscreen: "Exit full screen",
  controls: "Move & play",
  viewDistance: "Camera zoom",
  back: "Back to Team",
  loading: "Getting your world ready…",
  unavailable: "Team World could not open. Try again, or return to Team.",
  locked: "Check in for today’s plan to join your team.",
  connectedOnly: "Sign in to join Team World.",
  retry: "Try again",
  reconnect: "Reconnect",
  connectionPaused:
    "Shared play is paused while we reconnect. Movement and kicks are unavailable.",
  connectionStopped: "You’re disconnected. Reconnect to return to shared play.",
  states: {
    idle: "Ready to enter",
    connecting: "Joining your team…",
    ready: "Live together",
    reconnecting: "Reconnecting…",
    paused: "Play paused while we reconnect",
    denied: "This room is unavailable",
    failed: "Connection stopped",
    full: "Your world is full",
    left: "You left the world",
  },
  path: "Tap or hold to travel",
  joystick: "Joystick",
  sprint: "Pace · automatic",
  stop: "Stop",
  kick: "Kick ball",
  use: "Use tool",
  stow: "Stow",
  draw: "Draw",
  equipment: "Equipment",
  expression: "Expression",
  movement: "Movement mode",
  empty: "Empty hands",
  cancel: "Stop expression",
  people: (n: number) => `${n} ${n === 1 ? "player" : "players"}`,
  tools: [
    { id: "tether-winch", label: "Tether winch" },
    { id: "rebound-panel", label: "Rebound panel" },
    { id: "wake-driver", label: "Wake driver" },
  ],
  emotes: [
    { id: "wave", label: "Wave" },
    { id: "cheer", label: "Cheer" },
    { id: "dance", label: "Dance" },
  ],
  hint: "Push a ball into the cannon’s rear intake. Hold a tool’s action, then release.",
} as const;
