export const worldCopy = {
  navigation: {
    path: "Click or tap the ground to move",
    joystick: "Drag the pad to move · point to aim",
    landing: "Landing first · your next destination is queued",
    complex: "That route is too complex. Try a nearer spot.",
    unreachable: "No walking route to that spot",
    moving: "On the way · tap somewhere else to redirect",
    arriving: "Arriving…",
    arrived: "You’re here · choose your next move",
    sprint: "Sprint",
    sprintOn: "Sprint · on",
  },
  title: "Team World",
  fullscreen: "Full screen",
  exitFullscreen: "Exit full screen",
  controls: "Move & play",
  viewDistance: "Camera zoom",
  back: "Back to Team",
  loading: "Getting your world ready…",
  unavailable: "Team World could not open. Try again, or return to Team.",
  locked: "Check in for today’s plan to join your team.",
  connectedOnly: "Sign in to join Team World.",
  retry: "Try again",
  states: {
    idle: "Ready to enter",
    connecting: "Joining your team…",
    ready: "Live together",
    reconnecting: "Reconnecting…",
    paused: "Play paused while we reconnect",
    denied: "This room is unavailable",
    failed: "Connection stopped",
    full: "Your world is full",
    left: "You left the world",
  },
  path: "Tap to walk",
  joystick: "Joystick",
  sprint: "Sprint",
  stop: "Stop",
  kick: "Kick ball",
  use: "Use tool",
  stow: "Stow",
  draw: "Draw",
  equipment: "Equipment",
  expression: "Expression",
  movement: "Movement mode",
  empty: "Empty hands",
  cancel: "Stop expression",
  people: (n: number) => `${n} ${n === 1 ? "player" : "players"}`,
  tools: [
    { id: "tether-winch", label: "Tether winch" },
    { id: "rebound-panel", label: "Rebound panel" },
    { id: "wake-driver", label: "Wake driver" },
  ],
  emotes: [
    { id: "wave", label: "Wave" },
    { id: "cheer", label: "Cheer" },
    { id: "dance", label: "Dance" },
  ],
  hint: "Push a ball into the cannon’s rear intake. Hold a tool’s action, then release.",
} as const;
