export const momentumAlphaCopy = {
  brand: "ZoomiGo",
  edition: "Momentum Alpha",
  alternateView: "Alternate view",
  nav: {
    label: "Momentum Alpha navigation",
    today: "Today",
    team: "Team",
    me: "Me",
  },
  today: {
    flowEyebrow: "Stay in today’s flow",
    eyebrow: "Chosen for your next step",
    title: "Today’s plan",
    goalNote: "Completes today’s plan",
    stretchNote: "Optional if every rep still feels smooth",
    checkIn: "Check in",
    alternative: "Choose another activity",
    alternativeTitle: "Choose an approved alternative",
    alternativeIntro:
      "Choose what fits today. You can see the Momentum effect before deciding.",
    alternativeBack: "Keep today’s plan",
    why: "Why this plan",
  },
  trail: {
    personal: "Personal Momentum",
    team: "Team Momentum",
    bands: {
      "warming-up": "Warming up",
      building: "Building",
      rolling: "Rolling",
      strong: "Strong",
    },
    personalDetail: {
      "warming-up": "A new rhythm is taking shape",
      building: "You’re finding a steadier rhythm",
      rolling: "You’re following a steady rhythm",
      strong: "Your recent plan-following is strong",
    },
    teamDetail: "More teammates are finding their rhythm",
  },
  checkIn: {
    targetGroup: "Completed target",
    eyebrow: "Quick check-in",
    title: "What did you complete?",
    feeling: "How do you feel now?",
    feelings: {
      good: "Good",
      tired: "Tired",
      "very-tired": "Very tired",
    },
    goalNote: "Complete",
    stretchNote: "Optional small private lift",
    privacy: "Your result and recovery signal stay private.",
    save: "Save check-in",
    back: "Back to today",
  },
  complete: {
    eyebrow: "Personal Momentum moved",
    title: "Main work complete",
    prescribedGoal: "Full movement for completing the goal",
    prescribedStretch: "Small private lift for the optional stretch",
    partial: "Partial movement for an approved alternative",
    equivalent: "Full movement for a safety-equivalent alternative",
    team: "Your appropriate plan added one normalized lift to Team Momentum.",
    recoveryEyebrow: "The right next move",
    recoveryBody:
      "Relaxed pace. This supports recovery and adds no second Team lift.",
    logRecovery: "Log recovery",
    recoveryLogged: "Recovery logged",
    seeTeam: "See Team Momentum",
    finish: "Finish for today",
    extraTitle: "Record more activity",
    extraBody:
      "Approved activity can stay in private history. It will not move personal or Team Momentum again today.",
    extraSaved: "Saved to private history",
  },
  rest: {
    eyebrow: "Today’s appropriate plan",
    title: "Rest is today’s plan",
    body: "Rest protects the rhythm. Recording it needs no performance result or explanation.",
    action: "Record rest day",
    completeEyebrow: "Personal Momentum held steady",
    completeTitle: "Rest recorded",
    completeBody: "Today’s plan is complete. Nothing else is suggested.",
    privacy: "Private, structured, and complete with one tap.",
    seeTeam: "See Team Momentum",
  },
  team: {
    eyebrow: "Shared energy · private results",
    title: "Hill Striders Momentum",
    pulseTitle: "Steady together",
    followers: (count: number) =>
      `${count} teammates recently followed the plan that was right for them.`,
    highlightTitle: "Steady strides",
    highlightEyebrow: "Rotating team highlight",
    highlightBody:
      "This rotating group followed several recent plan opportunities. More teammates get a turn as the rhythm continues.",
    privacy:
      "No targets, results, tiredness, rest identity, or ordered placement.",
    playerRhythms: ["Kept a steady rhythm", "Followed their plan"],
  },
  me: {
    eyebrow: "Momentum Alpha profile",
    historyEyebrow: "Only you and authorized adults",
    historyTitle: "Private activity",
    historyEmpty: "Today’s activity will appear here after check-in.",
    privateBadge: "Private",
    reviewEyebrow: "Local review controls",
    reviewTitle: "Preview another plan state",
    reviewBody:
      "These controls appear only in local development and do not ship in the production build.",
    trainingDay: "Training day",
    restDay: "Rest day",
    reset: "Reset today’s mock plan",
  },
} as const;
