/** Console copy, kept out of `copy.ts` so the player bundle does not carry
 * wording only a coach or an operator will ever read (REQ-401). */
export const staffCopy = {
  signInTitle: "Coach and staff sign in",
  signInIntro:
    "This page is for coaches and staff. Players sign in by scanning their QR code.",
  playerLink: "Player sign in",
  emailLabel: "Email address",
  passwordLabel: "Password",
  continue: "Continue",
  working: "Working…",
  back: "Back",
  codeTitle: "Enter your authenticator code",
  codeIntro:
    "Open the authenticator app you enrolled and enter the six-digit code it shows for ZoomiGo.",
  codeLabel: "Six-digit code",
  signIn: "Sign in",
  // One message for every failure, so that guessing at addresses never
  // reveals which staff accounts exist (REQ-106).
  signInFailed: "That did not work. Check the details and try again.",
  tooManyAttempts: "Too many attempts. Wait a few minutes and try again.",
  setupRequiredTitle: "Finish setting up your account",
  setupRequiredBody:
    "This account still needs a password and an authenticator. Open the one-time setup link the operator gave you, exactly as it was given, including everything after the #.",
  setup: {
    title: "Set up your staff account",
    intro:
      "You need the temporary password the operator gave you and an authenticator app on your phone.",
    missingToken:
      "This page needs the one-time setup link. Open the link the operator gave you exactly as it was given, including everything after the #.",
    temporaryPasswordLabel: "Temporary password",
    enrollTitle: "Add ZoomiGo to your authenticator",
    enrollIntro:
      "Add this account to your authenticator app using the setup key below, then choose a password and enter the code the app shows.",
    accountLabel: "Account",
    secretLabel: "Setup key",
    uriLabel: "Or open this in your authenticator app",
    newPasswordLabel: "New password",
    confirmPasswordLabel: "Repeat new password",
    passwordRule: "Use at least 12 characters.",
    passwordTooShort: "Use at least 12 characters.",
    passwordMismatch: "The two passwords do not match.",
    codeRule: "Enter the six-digit code from your authenticator.",
    finish: "Finish setup",
    failed: "That did not work. Check the details and try again.",
    recoveryTitle: "Save your recovery codes",
    recoveryBody:
      "These codes are shown only now and can never be shown again. Save them somewhere safe. Each one can be used once if you lose your authenticator.",
    recoveryAcknowledge: "I have saved these codes somewhere safe",
    recoveryContinue: "Continue to the console",
  },
} as const;

export const consoleCopy = {
  eyebrow: "Staff console",
  signOut: "Sign out",
  signOutHint: "Sign out before you hand this device to anyone else.",
  loading: "Loading…",
  loadFailed: "That could not be loaded.",
  actionFailed: "That did not work. Try again.",
  retry: "Try again",
  cancel: "Cancel",
  close: "Close",
  home: {
    coachTitle: "Coach console",
    coachBody:
      "The coach console is still being built. Rosters, assignments, and assessments arrive in a later release. Until then, ask the operator for anything you need changed.",
    teams: "Your teams",
    noTeams: "No teams are assigned to this account yet.",
    signedInAs: (email: string) => `Signed in as ${email}`,
    openAdmin: "Open the operator console",
  },
  admin: {
    title: "Operator console",
    intro: "Find a player or a team, then repair it on one screen.",
    searchLabel: "Search players and teams",
    searchHint: "Searches every club by name.",
    searchAction: "Search",
    searchEmpty: "No players or teams matched that search.",
    playersHeading: "Players",
    teamsHeading: "Teams",
    clubs: "Clubs",
    teams: "Teams",
    accounts: "Staff accounts",
    audit: "Audit trail",
    backToSearch: "Back to search",
  },
  credential: {
    heading: "Login",
    state: {
      none: "No login issued",
      active: "Login active",
      locked: "Login locked",
      revoked: "Login revoked",
    },
    issued: "Issued",
    lastUsed: "Last used",
    lockedUntil: "Locked until",
    failedAttempts: "Failed attempts",
    activeSessions: "Signed-in devices",
    unlock: "Unlock",
    reissue: "Reissue login",
    revoke: "Revoke login",
    reissueConfirm:
      "Reissuing signs this player out everywhere and replaces their printed code. Continue?",
    revokeConfirm:
      "Revoking ends this player's sign-in. They cannot sign in again until a new code is issued. Continue?",
  },
  reveal: {
    title: "Print or photograph this now",
    warning:
      "This is shown once and can never be shown again. If you close it before saving it, you will have to reissue the login.",
    pinLabel: "PIN",
    qrAlt: "Personal sign-in QR code",
    linkLabel: "Sign-in link",
    done: "I have saved this",
  },
  player: {
    title: "Player",
    club: "Club",
    memberships: "Team memberships",
    noMemberships: "This player is not on a team.",
    from: "From",
    to: "To",
    endMembership: "End membership",
    endMembershipConfirm:
      "Ending this membership takes the player off this team's roster, leaderboards, and team activity. Their account and their own history stay. Continue?",
    events: "Recent sign-in events",
    noEvents: "No sign-in events recorded.",
    deactivateHeading: "Deactivate account",
    deactivateBody:
      "Deactivation ends this account. It does not erase any data. Type the player's first name and last initial exactly as they appear above to confirm.",
    deactivateLabel: "Type the player's name to confirm",
    deactivate: "Deactivate account",
    deactivateMismatch: "That name does not match. Nothing was changed.",
    deactivated: "This account is deactivated.",
  },
  stepUp: {
    title: "Confirm it is you",
    body: "This action needs your password and a fresh authenticator code.",
    confirm: "Confirm",
    failed: "That did not work. Try again.",
  },
  clubs: {
    title: "Clubs",
    nameLabel: "Club name",
    create: "Create club",
    teamCount: (count: number) => `${count} team${count === 1 ? "" : "s"}`,
    empty: "No clubs yet.",
  },
  teams: {
    title: "Teams",
    create: "Create team",
    edit: "Edit team",
    editing: (name: string) => `Editing ${name}`,
    nameLabel: "Team name",
    clubLabel: "Club",
    seasonLabel: "Season",
    timeZoneLabel: "Time zone",
    weeklyGoalLabel: "Weekly goal (sessions)",
    playerCount: (count: number) => `${count} player${count === 1 ? "" : "s"}`,
    empty: "No teams yet.",
    needsClub: "Create a club before you create a team.",
    openRoster: "Open roster",
    save: "Save team",
    // F-O4: the time zone decides what "today" is for every date on the team.
    timeZoneWarning: (from: string, to: string) =>
      `Changing the time zone from ${from} to ${to} changes what “today” means for this team. Every date on this team, and the 24-hour window in which a player may delete an entry, is judged in the team's time zone.`,
    timeZoneConfirm: "Save the time-zone change",
  },
  roster: {
    title: "Roster",
    empty: "No players on this team yet.",
    lastActivity: "Last activity",
    never: "No activity yet",
    openPlayer: "Open player",
    addExisting: "Add an existing player",
    addExistingHint:
      "Search for a player who already has an account, then add them to this team.",
    add: "Add to team",
    added: "Added to the team.",
    provision: "Provision a new player",
    provisionHint:
      "First name and last initial only. The PIN and printable code are revealed once.",
    firstNameLabel: "First name",
    lastInitialLabel: "Last initial",
    provisionAction: "Create player and reveal code",
    provisionLocked: "Provisioning players is not approved on this deployment.",
    endMembership: "End membership",
  },
  accounts: {
    title: "Staff accounts",
    emailLabel: "Email address",
    clubLabel: "Club",
    roleLabel: "Role",
    roles: {
      coach: "Coach",
      club_admin: "Club manager",
      platform_admin: "Operator",
    },
    create: "Create account",
    reset: "Reset credentials",
    resetConfirm:
      "Resetting signs this account out everywhere and needs a new setup link and temporary password. Continue?",
    empty: "No staff accounts yet.",
    setupComplete: "Setup complete",
    setupPending: "Setup not finished",
    lastUsed: "Last used",
    assignments: "Team assignments",
    assign: "Assign to a team",
    unassign: "Unassign",
    invitationTitle: "Hand these over now",
    invitationWarning:
      "The setup link and temporary password are shown once and can never be shown again.",
    setupUrlLabel: "Setup link",
    temporaryPasswordLabel: "Temporary password",
    expiresAt: "Expires",
  },
  audit: {
    title: "Audit trail",
    accountLabel: "Account id",
    sinceLabel: "Since",
    limitLabel: "Rows",
    apply: "Apply",
    empty: "No audit events matched.",
    occurredAt: "When",
    actor: "Actor",
    action: "Action",
    target: "Target",
    detail: "Detail",
  },
} as const;
