export const copy = {
  brand: "ZoomiGo",
  tagline: "Show up. Build your stride.",
  safeSocial: "Team views celebrate participation—not speed or scores.",
  saveSuccess: "Training saved",
  hillSprintInstructions: [
    "Find a short hill with clear footing and room to slow down safely.",
    "Run uphill fast for 6 seconds. Stop before your form gets sloppy.",
    "Walk slowly back to the start, then wait until your breathing feels calm.",
    "Repeat 8 times. Finish with an easy walk and some water.",
  ],
  streakQuips: [
    "If each streak day were a hammerhead shark, your streak would be {value} feet long!",
    "If each streak day were a soccer ball, your streak would stretch {value} feet!",
    "If each streak day were a giant taco, you would have a {value}-foot snack tower!",
  ],
  feelingQuestions: {
    effort: "How hard did you work?",
    exhaustion: "How tired were you after?",
  },
  allEffortCounts: "Every player’s effort counts.",
  recoveryNote:
    "Feeling worn out? Hydrate, take it easy, and check with a parent or coach.",
  noEditing:
    "Saved entries cannot be edited. Recent entries can be deleted and re-entered.",
  auth: {
    opening: "Opening ZoomiGo…",
    unavailableTitle: "ZoomiGo is taking a breather",
    unavailableBody: "Please try again in a moment.",
    loginTitle: "Player sign in",
    loginIntro: "Scan your personal QR code, then enter your four-digit PIN.",
    pinLabel: "Four-digit PIN",
    remember: "Remember this device for 30 days",
    missingQR: "Scan your player QR code first.",
    invalidPIN: "Enter the four-digit PIN from your parent or coach.",
    help: "Need help? Ask a parent or coach to reissue your QR code.",
  },
  social: {
    teamLoading: "Loading team progress…",
    teamError: "Team progress could not be loaded.",
    leaderboardLoading: "Loading leaderboard…",
    leaderboardError: "The leaderboard could not be loaded.",
    retry: "Try again",
    weeklyGoal: "This week’s goal",
    dueSunday: "◇ By Sunday",
    consistencyBadge: "✦ 3 active days in 5 = Consistency badge",
    safePoints: "safe participation points",
    noParticipation: "No participation has been recorded for this period yet.",
  },
} as const;
