export const teamCanvasCopy = {
  brand: "ZoomiGo",
  edition: "Team Canvas",
  openProfile: (name: string) => `Open ${name}’s profile`,
  today: {
    eyebrow: "Today · Aug 20",
    trainingTitle: "Hill sprints",
    trainingDescription:
      "Sprint for 6 seconds, then walk back fully before the next start.",
    trainingContext: "Demanding · assigned cooldown follows",
    goal: "Goal · 8 reps",
    reach: "Reach · 10 reps",
    addLabel: "Record today’s plan",
    formTitle: "What did you complete?",
    save: "Save workout",
    alternative: "Coach-approved alternative",
    feel: {
      title: "How did it feel?",
      effortLow: "Easy",
      effortHigh: "All out",
      tirednessLow: "Fresh",
      tirednessHigh: "Drained",
      effort: [
        "😌 Super easy",
        "🙂 Easy",
        "🙂 Steady",
        "😅 Hard",
        "😤 Very hard",
        "🥵 Super hard",
        "🫠 All out",
      ],
      tiredness: [
        "😄 Fresh",
        "🙂 Slightly tired",
        "🙂 A little tired",
        "😮‍💨 Tired",
        "😫 Very tired",
        "🥱 Worn out",
        "🫠 Drained",
      ],
    },
    cooldownEyebrow: "One good finish",
    cooldownTitle: "Cool down",
    cooldownDescription:
      "Walk easily for 10 minutes. Keep the pace relaxed after today’s demanding work.",
    cooldownContext: "Your workout is saved · Team is unlocked",
    cooldownAction: "Record cooldown",
    joinTeam: "Join Team now",
    restEyebrow: "Today · planned recovery",
    restTitle: "Rest day",
    restDescription:
      "Recovery is today’s plan. Record it when you’ve protected the day.",
    restAction: "Record rest and join Team",
  },
  locked: {
    title: "Finish today first",
    body: "Record today’s workout or planned rest to open the team canvas.",
    action: "Back to today",
  },
  board: {
    eyebrow: "This week together",
    title: "Hill Striders",
    canvasLabel: "Hill Striders weekly canvas",
    week: "Mon—Sun",
    liveNow: "Live now",
    moveHint:
      "Move your avatar anytime. Tap your stamp to edit it; tap again to rest it in place.",
    physicsHint:
      "Move your avatar into a ball, balloon, or rocket to send it through the live scene.",
    stampTitle: "Team stamps",
    emptyReward: "Reach the stretch or finish the cooldown to earn a stamp.",
    placedReward: "Your live stamps can move until tomorrow’s workout arrives.",
    rewardReady: (count: number) =>
      `${count} ${count === 1 ? "stamp" : "stamps"} ready`,
    chooseStamp: (label: string) => `Choose ${label} stamp`,
    editStamp: (label: string) =>
      `Edit ${label} live stamp. Tap to rest it; use arrow keys to move, plus or minus to resize, brackets to rotate, or Delete to remove it.`,
    trashTarget: "Drop here to delete today’s stamp",
    moveAvatar: (name: string) => `Move ${name}’s avatar`,
    completedDays: (name: string) => `${name}’s completed days this week`,
    paletteLabel: "Stamp controls",
    smaller: "Smaller",
    larger: "Larger",
    rotateLeft: "Rotate left",
    rotateRight: "Rotate right",
    loading: "Opening the live team canvas…",
    connectedError: "The live canvas is having trouble syncing.",
    toolbox: {
      title: "Developer canvas toolbox",
      summary: "Change the controlled ‘random’ look",
      background: "Background scene",
      backgroundColor: "Fallback color",
      textColor: "Team-name color",
      textSize: "Team-name size",
      textStyle: "Team-name style",
      stamps: "Today’s five stamps",
      apply: "Apply to live canvas",
    },
  },
  me: {
    eyebrow: "Player profile",
    historyTitle: "Private activity",
    historyEmpty: "Your recorded days and extra activities will appear here.",
    viewLabel: "App view",
    reviewTitle: "Local review",
    reviewBody: "Preview a fresh training or rest day on this device only.",
    trainingDay: "Training day",
    restDay: "Rest day",
    reset: "Reset prototype",
    extraTitle: "Record something extra",
    extraLabel: "Extra activity",
    extraSave: "Save privately",
  },
} as const;
