export const teamCanvasCopy = {
  brand: "ZoomiGo",
  edition: "Team Canvas",
  openProfile: (name: string) => `Open ${name}’s profile`,
  today: {
    eyebrow: "Today · Aug 20",
    trainingTitle: "Hill sprints",
    trainingDescription:
      "Sprint for 6 seconds, then walk back fully before the next start.",
    trainingContext: "Demanding · assigned cooldown follows",
    goal: "Goal · 8 reps",
    reach: "Reach · 10 reps",
    addLabel: "Record today’s plan",
    formTitle: "What did you complete?",
    effort: "Effort",
    tiredness: "Tiredness",
    save: "Save and join Team",
    alternative: "Coach-approved alternative",
    restEyebrow: "Today · planned recovery",
    restTitle: "Rest day",
    restDescription:
      "Recovery is today’s plan. Record it when you’ve protected the day.",
    restAction: "Record rest and join Team",
  },
  locked: {
    title: "Finish today first",
    body: "Record today’s workout or planned rest to open the team canvas.",
    action: "Back to today",
  },
  board: {
    eyebrow: "This week together",
    title: "Hill Striders",
    canvasLabel: "Hill Striders weekly canvas",
    moveHint: "Drag your avatar anywhere. Confirmed stamps stay put.",
    emptyReward: "Reach the stretch or finish the cooldown to earn a stamp.",
    rewardReady: (count: number) =>
      `${count} ${count === 1 ? "stamp" : "stamps"} ready`,
    chooseStamp: (emoji: string) => `Choose ${emoji} stamp`,
    size: "Size",
    rotation: "Rotate",
    confirm: "Paste stamp",
    cancel: "Cancel",
    cooldownAction: "Record cooldown",
    cooldownTitle: "Easy recovery walk · 10 minutes",
    cooldownBody: "Relaxed pace after today’s demanding assignment.",
    cooldownSave: "Save cooldown",
    cooldownDone: "Cooldown recorded",
  },
  me: {
    eyebrow: "Player profile",
    historyTitle: "Private activity",
    historyEmpty: "Your recorded days and extra activities will appear here.",
    viewLabel: "App view",
    reviewTitle: "Local review",
    reviewBody: "Preview a fresh training or rest day on this device only.",
    trainingDay: "Training day",
    restDay: "Rest day",
    reset: "Reset prototype",
    extraTitle: "Record something extra",
    extraLabel: "Extra activity",
    extraSave: "Save privately",
  },
} as const;
