export const teamCanvasMock = {
  player: {
    id: "mason",
    firstName: "Mason",
    lastInitial: "C.",
    initials: "MC",
    avatarColor: "#ff785a",
    weeklySessions: 0,
    effortPoints: 0,
    currentStreak: 0,
    consistency: 0,
  },
  team: {
    id: "team-hill-striders",
    name: "Hill Striders",
  },
  completers: [
    {
      id: "player-ari",
      name: "Ari",
      initials: "AR",
      color: "#4f7cff",
      x: 20,
      y: 22,
      stars: 4,
    },
    {
      id: "player-elena",
      name: "Elena",
      initials: "EL",
      color: "#9d62d8",
      x: 73,
      y: 24,
      stars: 3,
    },
    {
      id: "player-noah",
      name: "Noah",
      initials: "NO",
      color: "#e9a62d",
      x: 27,
      y: 56,
      stars: 5,
    },
    {
      id: "player-zoe",
      name: "Zoe",
      initials: "ZO",
      color: "#2d9b77",
      x: 76,
      y: 61,
      stars: 2,
    },
  ],
  lockedStamps: [
    { id: "team-stamp-1", emoji: "⚡", x: 45, y: 18, size: 38, rotation: -14 },
    { id: "team-stamp-2", emoji: "🌟", x: 54, y: 63, size: 34, rotation: 12 },
    { id: "team-stamp-3", emoji: "🦁", x: 13, y: 78, size: 42, rotation: -6 },
  ],
  extras: [
    { id: "ball-touches" as const, label: "Easy ball touches · 10 minutes" },
    { id: "easy-walk" as const, label: "Easy walk · 15 minutes" },
    { id: "mobility" as const, label: "Mobility routine · 8 minutes" },
  ],
} as const;
