export const teamLoungeV2Copy = {
  label: "Team Lounge",
  theme: "Beach Boardwalk",
  regionLabel: "Beach Boardwalk Team Lounge",
  preview: "V2 · Local Canvas preview",
  shared: "V2 · Shared Canvas room",
  loading: "Setting up the boardwalk…",
  ready: "Press your player, then drag to move.",
  reconnecting: "Rejoining the team…",
  unavailable: "The boardwalk could not open.",
  retry: "Try again",
  emotes: "Emotes",
  stamps: "Stamps",
  items: "Items",
  map: "Map",
  mapHint: "This room fits on one screen.",
  itemsHint: "Props arrive in a later V2 slice.",
  localHint: "Local physics preview · teammates and persistence come next",
  sharedHint: "Live team room · the boardwalk ball persists between visits",
} as const;
