export const teamLoungeV2Copy = {
  label: "Team Lounge",
  theme: "Beach Boardwalk",
  regionLabel: "Beach Boardwalk Team Lounge",
  preview: "V2 · Local Canvas preview",
  shared: "V2 · Shared Canvas room",
  loading: "Setting up the boardwalk…",
  ready: "Press your player, then drag to move.",
  reconnecting: "Rejoining the team…",
  unavailable: "The boardwalk could not open.",
  retry: "Try again",
  emotes: "Emotes",
  stamps: "Stamps",
  items: "Items",
  map: "Map",
  mapHint: "This room fits on one screen.",
  itemsHint: "Props arrive in a later V2 slice.",
  localHint: "Local physics preview · teammates and persistence come next",
  sharedHint: "Live team room · the boardwalk ball persists between visits",
  placementError: "That stamp could not be placed. Pick a spot and try again.",
  placementErrors: {
    stamp_unavailable: "That stamp is not in your collection.",
    stamp_invalid_placement: "Choose one of the glowing lounge spots.",
    stamp_invalid_scale: "Keep your stamp between the small and large limits.",
    stamp_invalid_rotation: "Choose left, straight, or right for your stamp.",
    stamp_already_placed: "You already left a stamp here this week.",
    stamp_editing_unavailable: "Only your own weekly stamp can be changed.",
    application_denied: "That stamp could not be placed right now.",
  } as Record<string, string>,
} as const;
